import {MigrationInterface, QueryRunner} from "typeorm";

export class UserFullName1563487665398 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query("CREATE TABLE `status` (`id` int NOT NULL AUTO_INCREMENT, `title` varchar(100) NOT NULL, `description` varchar(100) NOT NULL, `baseStatus` int NOT NULL, `order` int NOT NULL, `creatorId` int NOT NULL, `projectId` int NOT NULL, `createdAt` datetime NOT NULL, `lastUpdated` datetime NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `company_membership` (`id` int NOT NULL AUTO_INCREMENT, `userId` int NOT NULL, `companyId` int NOT NULL, `joiningDate` datetime NOT NULL, `leavingDate` datetime NULL, `status` int NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `membership_request` (`id` int NOT NULL AUTO_INCREMENT, `userId` int NOT NULL, `companyId` int NOT NULL, `createdAt` datetime NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `company` (`id` int NOT NULL AUTO_INCREMENT, `name` varchar(100) NOT NULL, `description` varchar(100) NOT NULL, `ownerId` int NOT NULL, `createdAt` datetime NOT NULL, `lastUpdated` datetime NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `project_membership` (`id` int NOT NULL AUTO_INCREMENT, `userId` int NOT NULL, `projectId` int NOT NULL, `createdAt` datetime NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `project_manager` (`id` int NOT NULL AUTO_INCREMENT, `userId` int NOT NULL, `projectId` int NOT NULL, `createdAt` datetime NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `answer` (`id` int NOT NULL AUTO_INCREMENT, `content` varchar(100) NOT NULL, `creatorId` int NOT NULL, `questionId` int NOT NULL, `createdAt` datetime NOT NULL, `lastUpdated` datetime NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `question` (`id` int NOT NULL AUTO_INCREMENT, `title` varchar(100) NOT NULL, `content` varchar(100) NOT NULL, `creatorId` int NOT NULL, `projectId` int NOT NULL, `createdAt` datetime NOT NULL, `lastUpdated` datetime NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `project` (`id` int NOT NULL AUTO_INCREMENT, `title` varchar(300) NOT NULL, `description` varchar(300) NOT NULL, `prefix` varchar(3) NOT NULL, `createdAt` datetime NOT NULL, `lastUpdated` datetime NOT NULL, `companyId` int NOT NULL, `creatorId` int NOT NULL, `statusId` int NULL, `parentId` int NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `comment` (`id` int NOT NULL AUTO_INCREMENT, `content` varchar(400) NOT NULL, `taskId` int NOT NULL, `userId` int NOT NULL, `createdAt` datetime NOT NULL, `lastUpdated` datetime NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `task_assignment` (`id` int NOT NULL AUTO_INCREMENT, `userId` int NOT NULL, `taskId` int NOT NULL, `createdAt` datetime NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `label` (`id` int NOT NULL AUTO_INCREMENT, `name` varchar(15) NOT NULL, `createdAt` datetime NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `task_label` (`id` int NOT NULL AUTO_INCREMENT, `taskId` int NOT NULL, `labelId` int NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `task` (`id` int NOT NULL AUTO_INCREMENT, `title` varchar(100) NOT NULL, `description` varchar(100) NOT NULL, `code` int NOT NULL, `priority` int NOT NULL, `creatorId` int NOT NULL, `projectId` int NOT NULL, `statusId` int NOT NULL, `fromIssueId` int NULL, `createdAt` datetime NOT NULL, `lastUpdated` datetime NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `issue` (`id` int NOT NULL AUTO_INCREMENT, `title` varchar(100) NOT NULL, `description` varchar(100) NOT NULL, `creatorId` int NOT NULL, `projectId` int NOT NULL, `createdAt` datetime NOT NULL, `lastUpdated` datetime NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `user` (`id` int NOT NULL AUTO_INCREMENT, `name` varchar(100) NOT NULL, `surname` varchar(100) NOT NULL, `username` varchar(100) NOT NULL, `email` varchar(100) NOT NULL, `password` varchar(100) NOT NULL, `createdAt` datetime NOT NULL, `lastUpdated` datetime NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `status_template` (`id` int NOT NULL AUTO_INCREMENT, `name` varchar(100) NOT NULL, `creatorId` int NOT NULL, `companyId` int NOT NULL, `createdAt` datetime NOT NULL, `lastUpdated` datetime NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("CREATE TABLE `abstract_status` (`id` int NOT NULL AUTO_INCREMENT, `title` varchar(100) NOT NULL, `description` varchar(100) NOT NULL, `baseStatus` int NOT NULL, `order` int NOT NULL, `templateId` int NOT NULL, `createdAt` datetime NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB");
        await queryRunner.query("ALTER TABLE `status` ADD CONSTRAINT `FK_fc64c717604844ca00387a47ac2` FOREIGN KEY (`creatorId`) REFERENCES `user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `status` ADD CONSTRAINT `FK_14c9897451c5ecc91211a2e873d` FOREIGN KEY (`projectId`) REFERENCES `project`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `company_membership` ADD CONSTRAINT `FK_04d6d74f7813f87664530df55d5` FOREIGN KEY (`userId`) REFERENCES `user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `company_membership` ADD CONSTRAINT `FK_f29b709e2c7dd15a419f231ac75` FOREIGN KEY (`companyId`) REFERENCES `company`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `membership_request` ADD CONSTRAINT `FK_80820f18b2946333c3a930baff5` FOREIGN KEY (`userId`) REFERENCES `user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `membership_request` ADD CONSTRAINT `FK_4622a9032b18bf3f80e81711615` FOREIGN KEY (`companyId`) REFERENCES `company`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `company` ADD CONSTRAINT `FK_ee87438803acb531639e8284be0` FOREIGN KEY (`ownerId`) REFERENCES `user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `project_membership` ADD CONSTRAINT `FK_1d39ce9fa517b1123d11a87d24f` FOREIGN KEY (`userId`) REFERENCES `user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `project_membership` ADD CONSTRAINT `FK_64f251ee61ba7531396f34ba8af` FOREIGN KEY (`projectId`) REFERENCES `project`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `project_manager` ADD CONSTRAINT `FK_011d2b8525b86b6a0fceab5cec8` FOREIGN KEY (`userId`) REFERENCES `user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `project_manager` ADD CONSTRAINT `FK_f3fe19059edcc73587fff080aa7` FOREIGN KEY (`projectId`) REFERENCES `project`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `answer` ADD CONSTRAINT `FK_a1ae745d923bb87ea002eeb125a` FOREIGN KEY (`creatorId`) REFERENCES `user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `answer` ADD CONSTRAINT `FK_a4013f10cd6924793fbd5f0d637` FOREIGN KEY (`questionId`) REFERENCES `question`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `question` ADD CONSTRAINT `FK_ef0a5560abaa33606a4b87ab33e` FOREIGN KEY (`creatorId`) REFERENCES `user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `question` ADD CONSTRAINT `FK_04a6b839e7c50175802652de8e6` FOREIGN KEY (`projectId`) REFERENCES `project`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `project` ADD CONSTRAINT `FK_17c18aa92afa5fa328e9e181fe8` FOREIGN KEY (`companyId`) REFERENCES `company`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `project` ADD CONSTRAINT `FK_cfb02dac45e9dec5b82f960b3e3` FOREIGN KEY (`creatorId`) REFERENCES `user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `project` ADD CONSTRAINT `FK_b6d55aff9b16e061712260da686` FOREIGN KEY (`statusId`) REFERENCES `status`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `project` ADD CONSTRAINT `FK_972cc84102e4234fb489536fccf` FOREIGN KEY (`parentId`) REFERENCES `project`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `comment` ADD CONSTRAINT `FK_9fc19c95c33ef4d97d09b72ee95` FOREIGN KEY (`taskId`) REFERENCES `task`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `comment` ADD CONSTRAINT `FK_c0354a9a009d3bb45a08655ce3b` FOREIGN KEY (`userId`) REFERENCES `user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `task_assignment` ADD CONSTRAINT `FK_9b36540581f2d4b820cc481dc41` FOREIGN KEY (`userId`) REFERENCES `user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `task_assignment` ADD CONSTRAINT `FK_a1a927f2586253f3dd5145e105f` FOREIGN KEY (`taskId`) REFERENCES `task`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `task_label` ADD CONSTRAINT `FK_2ed786959519e4915b874d3677b` FOREIGN KEY (`taskId`) REFERENCES `task`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `task_label` ADD CONSTRAINT `FK_d63fe92803c283beac739102ff7` FOREIGN KEY (`labelId`) REFERENCES `label`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `task` ADD CONSTRAINT `FK_94fe6b3a5aec5f85427df4f8cd7` FOREIGN KEY (`creatorId`) REFERENCES `user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `task` ADD CONSTRAINT `FK_3797a20ef5553ae87af126bc2fe` FOREIGN KEY (`projectId`) REFERENCES `project`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `task` ADD CONSTRAINT `FK_02068239bb8d5b2fc7f3ded618c` FOREIGN KEY (`statusId`) REFERENCES `status`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `task` ADD CONSTRAINT `FK_28336a116dd7433693b861d3c61` FOREIGN KEY (`fromIssueId`) REFERENCES `issue`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `issue` ADD CONSTRAINT `FK_c45ed95b87402ee9e4b3c8dc81f` FOREIGN KEY (`creatorId`) REFERENCES `user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `issue` ADD CONSTRAINT `FK_be30b91466b730c5e25f1181f79` FOREIGN KEY (`projectId`) REFERENCES `project`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `status_template` ADD CONSTRAINT `FK_0016a0e0c122b62a89ce9d9386a` FOREIGN KEY (`creatorId`) REFERENCES `user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `status_template` ADD CONSTRAINT `FK_09a1c1d5416bf8edefdb89ebac7` FOREIGN KEY (`companyId`) REFERENCES `company`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `abstract_status` ADD CONSTRAINT `FK_f0ab2b3dd2dc28d01025677f892` FOREIGN KEY (`templateId`) REFERENCES `status_template`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query("ALTER TABLE `abstract_status` DROP FOREIGN KEY `FK_f0ab2b3dd2dc28d01025677f892`");
        await queryRunner.query("ALTER TABLE `status_template` DROP FOREIGN KEY `FK_09a1c1d5416bf8edefdb89ebac7`");
        await queryRunner.query("ALTER TABLE `status_template` DROP FOREIGN KEY `FK_0016a0e0c122b62a89ce9d9386a`");
        await queryRunner.query("ALTER TABLE `issue` DROP FOREIGN KEY `FK_be30b91466b730c5e25f1181f79`");
        await queryRunner.query("ALTER TABLE `issue` DROP FOREIGN KEY `FK_c45ed95b87402ee9e4b3c8dc81f`");
        await queryRunner.query("ALTER TABLE `task` DROP FOREIGN KEY `FK_28336a116dd7433693b861d3c61`");
        await queryRunner.query("ALTER TABLE `task` DROP FOREIGN KEY `FK_02068239bb8d5b2fc7f3ded618c`");
        await queryRunner.query("ALTER TABLE `task` DROP FOREIGN KEY `FK_3797a20ef5553ae87af126bc2fe`");
        await queryRunner.query("ALTER TABLE `task` DROP FOREIGN KEY `FK_94fe6b3a5aec5f85427df4f8cd7`");
        await queryRunner.query("ALTER TABLE `task_label` DROP FOREIGN KEY `FK_d63fe92803c283beac739102ff7`");
        await queryRunner.query("ALTER TABLE `task_label` DROP FOREIGN KEY `FK_2ed786959519e4915b874d3677b`");
        await queryRunner.query("ALTER TABLE `task_assignment` DROP FOREIGN KEY `FK_a1a927f2586253f3dd5145e105f`");
        await queryRunner.query("ALTER TABLE `task_assignment` DROP FOREIGN KEY `FK_9b36540581f2d4b820cc481dc41`");
        await queryRunner.query("ALTER TABLE `comment` DROP FOREIGN KEY `FK_c0354a9a009d3bb45a08655ce3b`");
        await queryRunner.query("ALTER TABLE `comment` DROP FOREIGN KEY `FK_9fc19c95c33ef4d97d09b72ee95`");
        await queryRunner.query("ALTER TABLE `project` DROP FOREIGN KEY `FK_972cc84102e4234fb489536fccf`");
        await queryRunner.query("ALTER TABLE `project` DROP FOREIGN KEY `FK_b6d55aff9b16e061712260da686`");
        await queryRunner.query("ALTER TABLE `project` DROP FOREIGN KEY `FK_cfb02dac45e9dec5b82f960b3e3`");
        await queryRunner.query("ALTER TABLE `project` DROP FOREIGN KEY `FK_17c18aa92afa5fa328e9e181fe8`");
        await queryRunner.query("ALTER TABLE `question` DROP FOREIGN KEY `FK_04a6b839e7c50175802652de8e6`");
        await queryRunner.query("ALTER TABLE `question` DROP FOREIGN KEY `FK_ef0a5560abaa33606a4b87ab33e`");
        await queryRunner.query("ALTER TABLE `answer` DROP FOREIGN KEY `FK_a4013f10cd6924793fbd5f0d637`");
        await queryRunner.query("ALTER TABLE `answer` DROP FOREIGN KEY `FK_a1ae745d923bb87ea002eeb125a`");
        await queryRunner.query("ALTER TABLE `project_manager` DROP FOREIGN KEY `FK_f3fe19059edcc73587fff080aa7`");
        await queryRunner.query("ALTER TABLE `project_manager` DROP FOREIGN KEY `FK_011d2b8525b86b6a0fceab5cec8`");
        await queryRunner.query("ALTER TABLE `project_membership` DROP FOREIGN KEY `FK_64f251ee61ba7531396f34ba8af`");
        await queryRunner.query("ALTER TABLE `project_membership` DROP FOREIGN KEY `FK_1d39ce9fa517b1123d11a87d24f`");
        await queryRunner.query("ALTER TABLE `company` DROP FOREIGN KEY `FK_ee87438803acb531639e8284be0`");
        await queryRunner.query("ALTER TABLE `membership_request` DROP FOREIGN KEY `FK_4622a9032b18bf3f80e81711615`");
        await queryRunner.query("ALTER TABLE `membership_request` DROP FOREIGN KEY `FK_80820f18b2946333c3a930baff5`");
        await queryRunner.query("ALTER TABLE `company_membership` DROP FOREIGN KEY `FK_f29b709e2c7dd15a419f231ac75`");
        await queryRunner.query("ALTER TABLE `company_membership` DROP FOREIGN KEY `FK_04d6d74f7813f87664530df55d5`");
        await queryRunner.query("ALTER TABLE `status` DROP FOREIGN KEY `FK_14c9897451c5ecc91211a2e873d`");
        await queryRunner.query("ALTER TABLE `status` DROP FOREIGN KEY `FK_fc64c717604844ca00387a47ac2`");
        await queryRunner.query("DROP TABLE `abstract_status`");
        await queryRunner.query("DROP TABLE `status_template`");
        await queryRunner.query("DROP TABLE `user`");
        await queryRunner.query("DROP TABLE `issue`");
        await queryRunner.query("DROP TABLE `task`");
        await queryRunner.query("DROP TABLE `task_label`");
        await queryRunner.query("DROP TABLE `label`");
        await queryRunner.query("DROP TABLE `task_assignment`");
        await queryRunner.query("DROP TABLE `comment`");
        await queryRunner.query("DROP TABLE `project`");
        await queryRunner.query("DROP TABLE `question`");
        await queryRunner.query("DROP TABLE `answer`");
        await queryRunner.query("DROP TABLE `project_manager`");
        await queryRunner.query("DROP TABLE `project_membership`");
        await queryRunner.query("DROP TABLE `company`");
        await queryRunner.query("DROP TABLE `membership_request`");
        await queryRunner.query("DROP TABLE `company_membership`");
        await queryRunner.query("DROP TABLE `status`");
    }

}
